### ISSUE TITLE
Selection Sort Algorithm

### ISSUE THREAD

**Issue by Tirent-user** [Tirent-user/Easy-DSA-and-Algo#16]
contribute for selection sort

**Comment by Ash0069** [comment]
Hi @Tirent-user, please assign this issue to me

**Comment by atharvabhoite7** [comment]
Hey @Tirent-user, I am interested in this. Please can you assign it to me

**Comment by MrJayendra** [comment]
I am interested in this task.
Please assign it to me

**Comment by isaacmtp** [comment]
made a pull request mate
do merge it
