### ISSUE TITLE
Searching algo codes #hacktoberfest

### ISSUE THREAD

**Issue by Tirent-user** [Tirent-user/Easy-DSA-and-Algo#2]
contribute to searching algorithms
#hacktoberfest

**Comment by a-akash-singh** [comment]
Hello @Tirent-user please assign this to me

**Comment by anubhavgaur8** [comment]
Hello @Tirent-user I have attached a binary search python file please review it and merge it.

**Comment by Keerthivardhan1** [comment]
can you assign this issue to me 
I will add linear search and Binary search algorithms  and there time and space  complexity.
